// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/GlimrDashboard.tsx": () => import("../components/mockups/dashboard/GlimrDashboard.tsx"),
  "./components/mockups/dashboard/GlimrStyle.tsx": () => import("../components/mockups/dashboard/GlimrStyle.tsx"),
  "./components/mockups/dashboard/V1LowRisk.tsx": () => import("../components/mockups/dashboard/V1LowRisk.tsx"),
  "./components/mockups/dashboard/V2PremiumSaaS.tsx": () => import("../components/mockups/dashboard/V2PremiumSaaS.tsx"),
  "./components/mockups/dashboard/V3Cosmic.tsx": () => import("../components/mockups/dashboard/V3Cosmic.tsx")
};
